### ISSUE TITLE
installation attempt fails: "error reading from connection"

### ISSUE THREAD

**Issue by mgastner** [ropensci/rnaturalearthhires#1] opened 2019-11-09 01:21 UTC
I'm trying to run the command `ne_countries(scale = 10)` in R 3.6.1. I'm encountering an error when trying to install rnaturalearthhires (see below). A Google search doesn't bring up information about what causes this error. Can you please advise?

```
> ne_countries(scale = 10)
The rnaturalearthhires package needs to be installed.
Install the rnaturalearthhires package? 

1: Yes
2: No

Selection: 1
Installing the rnaturalearthhires package.
Installing package into ‘/home/mgastner/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
Error in value[[3L]](cond) : 
  Failed to install the rnaturalearthhires package.
  Please try installing the package for yourself using the following command: 
     install.packages("rnaturalearthhires", repos = "http://packages.ropensci.org", type = "source")
> install.packages("rnaturalearthhires", repos = "http://packages.ropensci.org", type = "source")
Installing package into ‘/home/mgastner/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
Error in install.packages : error reading from connection
```

**Comment by pnewall** [comment] 2019-11-10 15:58
Ditto - same issue. Please advise.

**Comment by KushtrimVisoka** [comment] 2019-11-10 16:16
Same issue.

**Comment by JoseEchave** [comment] 2019-11-11 14:07
Try 
`devtools::install_github("ropensci/rnaturalearthhires") `
That worked for me

**Comment by mgastner** [comment] 2019-11-11 14:41
Thanks, @JoseEchave. Your suggestion indeed does the job.

**Comment by KushtrimVisoka** [comment] 2019-11-11 15:11
Thank you, @JoseEchave!

**Comment by afeierman** [comment] 2019-12-02 17:52
Could this be as simple as changing HTTP to HTTPS?

**Comment by Helmut01** [comment] 2020-01-30 17:40
> Could this be as simple as changing HTTP to HTTPS?

Unfortunately not.

**Comment by jgo23** [comment] 2020-07-11 10:49
Solved this by realising i hadn't set my working directory. Once set to a given location installation went without a problem.

**Comment by wangdafacai** [comment] 2021-04-21 03:20
> Try
> `devtools::install_github("ropensci/rnaturalearthhires") `
> That worked for me

Thanks bro

**Comment by zhxinc** [comment] 2021-05-29 15:29
> Try
> `devtools::install_github("ropensci/rnaturalearthhires") `
> That worked for me

for me it gets stuck on that line (nothing happens after a long time), do you maybe have any idea why?

**Comment by gifravari** [comment] 2021-07-27 14:39
a mi me funciono con esto:

devtools::install_github("ropensci/rnaturalearthdata")
install.packages("rnaturalearthhires",
                 repos = "http://packages.ropensci.org",
                 type = "source")

**Comment by trashbirdecology** [comment] 2021-11-25 23:02
Still no resolution for this? (I am able to successfully grab using install_github, but just curious wth is happening :D)

**Comment by patchcervan** [comment] 2022-11-15 06:26
This seems to work for me:

`install.packages("rnaturalearthhires", repos = "http://ropensci.r-universe.dev", type = "source")`

So probably it's just that the URL changed from "http://packages.ropensci.org" to "http://ropensci.r-universe.dev"?

**Comment by PMassicotte** [comment] 2024-09-09 13:19
Closing this. Please open a new issue if the problem is still there.

**Closed as completed by PMassicotte** 2024-09-09 13:19 UTC
